// <auto-generated />
using System;
using ApplicationCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApplicationCore.Migrations
{
    [DbContext(typeof(SistemaRrhhContext))]
    partial class SistemaRrhhContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplicationCore.Models.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("HoraEntrada")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("HoraSalida")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id")
                        .HasName("PK__Asistenc__3214EC079485D30E");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("ApplicationCore.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("PK__Cargo__3214EC0721FD1E19");

                    b.ToTable("Cargo", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Models.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PK__Contrato__3214EC079E281EC0");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Contrato", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Departam__3214EC0761F11BC9");

                    b.ToTable("Departamento", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CargoId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("PK__Empleado__3214EC0700716A1A");

                    b.HasIndex("CargoId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex(new[] { "Email" }, "UQ__Empleado__A9D105349DBE8487")
                        .IsUnique();

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Models.EvaluacionDesempeno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .HasColumnType("text");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaEvaluacion")
                        .HasColumnType("date");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Evaluaci__3214EC07BC8C1015");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("EvaluacionDesempeno", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Models.Nomina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Deducciones")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<decimal>("SalarioNeto")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Nomina__3214EC07A7CB722C");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Nomina", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Dias")
                        .HasColumnType("integer");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateOnly?>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Motivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("PK__Permiso__3214EC07FED0AEB1");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Permiso", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Models.Asistencia", b =>
                {
                    b.HasOne("ApplicationCore.Models.Empleado", "Empleado")
                        .WithMany("Asistencia")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("FK__Asistenci__Emple__4316F928");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ApplicationCore.Models.Contrato", b =>
                {
                    b.HasOne("ApplicationCore.Models.Empleado", "Empleado")
                        .WithMany("Contratos")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("FK__Contrato__Emplea__403A8C7D");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ApplicationCore.Models.Empleado", b =>
                {
                    b.HasOne("ApplicationCore.Models.Cargo", "Cargo")
                        .WithMany("Empleados")
                        .HasForeignKey("CargoId")
                        .IsRequired()
                        .HasConstraintName("FK__Empleado__CargoI__3D5E1FD2");

                    b.HasOne("ApplicationCore.Models.Departamento", "Departamento")
                        .WithMany("Empleados")
                        .HasForeignKey("DepartamentoId")
                        .IsRequired()
                        .HasConstraintName("FK__Empleado__Depart__3C69FB99");

                    b.Navigation("Cargo");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("ApplicationCore.Models.EvaluacionDesempeno", b =>
                {
                    b.HasOne("ApplicationCore.Models.Empleado", "Empleado")
                        .WithMany("EvaluacionDesempenos")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("FK__Evaluacio__Emple__4E88ABD4");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ApplicationCore.Models.Nomina", b =>
                {
                    b.HasOne("ApplicationCore.Models.Empleado", "Empleado")
                        .WithMany("Nominas")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("FK__Nomina__Empleado__45F365D3");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ApplicationCore.Models.Permiso", b =>
                {
                    b.HasOne("ApplicationCore.Models.Empleado", "Empleado")
                        .WithMany("Permisos")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("FK__Permiso__Emplead__4AB81AF0");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ApplicationCore.Models.Cargo", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("ApplicationCore.Models.Departamento", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("ApplicationCore.Models.Empleado", b =>
                {
                    b.Navigation("Asistencia");

                    b.Navigation("Contratos");

                    b.Navigation("EvaluacionDesempenos");

                    b.Navigation("Nominas");

                    b.Navigation("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
